/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "DIO.h"
#include "DIO_aliases.h"
#include "SIG.h"
#include "SIG_aliases.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "EEPROM.h"
#include "Timer1.h"
#include "Clock_2.h"
#include "USBUART_Dp.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dm_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

